import React,{useState} from 'react';
import Card from '../../components/Card/Card';
import Modals from '../../components/Modal';
const HomePage=(props)=>{
    const [shoes]=useState([{
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "color": "Black",
        "designer": "Peter Moore",
        "details": "Black/White-Medium Grey",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/011/119/994/original/218099_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 218099,
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/011/119/994/original/218099_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 1 Retro High OG 'Shadow' 2018",
        "nickname": "Shadow",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/011/119/994/original/218099_00.png.png",
        "product_template_id": 218099,
        "release_date": "2018-04-14T23:59:59.000Z",
        "release_date_unix": 1523750399,
        "release_year": 2018,
        "retail_price_cents": 16000,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "color": "Black",
        "designer": "Tinker Hatfield",
        "details": "Black/Cement Grey-Summit White-Fire Red",
        "gender": [
          "youth"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/020/806/444/original/507844_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 507844,
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/020/806/444/original/507844_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 4 Retro OG GS 'Bred' 2019",
        "nickname": "Bred",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/020/806/444/original/507844_00.png.png",
        "product_template_id": 507844,
        "release_date": "2019-05-04T23:59:59.000Z",
        "release_date_unix": 1557014399,
        "release_year": 2019,
        "retail_price_cents": 14000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Jordan 4",
        "size_range": [
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7
        ]
      },
      {
        "box_condition": "no_original_box",
        "brand_name": "Air Jordan",
        "category": [
          "basketball"
        ],

        "color": "Black",
        "designer": "Tinker Hatfield",
        "details": "Black/Concord-White",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/008/654/900/original/52015_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 52015,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/008/654/900/original/52015_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 11 Retro 'Space Jam' 2016",
        "nickname": "Space Jam",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/008/654/900/original/52015_00.png.png",
        "product_template_id": 52015,
        "release_date": "2016-12-09T23:59:59.000Z",
        "release_date_unix": 1481327999,
        "release_year": 2016,
        "retail_price_cents": 22000,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 11",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "no_original_box",
        "brand_name": "Air Jordan",
        "category": [
          "basketball"
        ],
        "color": "Red",
        "designer": "Tinker Hatfield",
        "details": "Gym Red/Black-White",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/008/870/353/original/235806_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 235806,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/008/870/353/original/235806_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 11 Retro 'Win Like '96'",
        "nickname": "Win Like '96",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/008/870/353/original/235806_00.png.png",
        "product_template_id": 235806,
        "release_date": "2017-12-09T23:59:59.000Z",
        "release_date_unix": 1512863999,
        "release_year": 2017,
        "retail_price_cents": 22000,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 11",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "no_original_box",
        "brand_name": "Air Jordan",
        "category": [
          "basketball"
        ],
        "color": "White",
        "designer": "Tinker Hatfield",
        "details": "White/Legend Blue",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/010/223/048/original/13607_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 13607,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/010/223/048/original/13607_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 11 Retro 'Legend Blue' 2014",
        "nickname": "Legend Blue",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/010/223/048/original/13607_00.png.png",
        "product_template_id": 13607,
        "release_date": "2014-12-20T23:59:59.000Z",
        "release_date_unix": 1419119999,
        "release_year": 2014,
        "retail_price_cents": 20000,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 11",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Black",
        "designer": "Peter Moore",
        "details": "Black/Black-Metallic Gold-White",
        "gender": [
          "women"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/021/545/481/original/509480_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 509480,
        "keywords": [
          "Panda",
          "Twist"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/021/545/481/original/509480_00.png.png",
        "midsole": "Air",
        "name": "Wmns Air Jordan 1 Retro High OG 'Twist'",
        "nickname": "Twist, Pony",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/021/545/481/original/509480_00.png.png",
        "product_template_id": 509480,
        "release_date": "2019-05-10T23:59:59.000Z",
        "release_date_unix": 1557532799,
        "release_year": 2019,
        "retail_price_cents": 16000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Jordan 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Black",
        "designer": "Peter Moore",
        "details": "Black/Varsity Red-Varsity Royal-White",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/012/910/690/original/554724_065.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 397517,
        "keywords": [
          "promoted1",
          "underRetail"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/012/910/690/original/554724_065.png.png",
        "midsole": "Air",
        "name": "Air Jordan 1 Mid 'Multicolor Swoosh Black'",
        "nickname": "Multicolor Swoosh Black",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/012/910/690/original/554724_065.png.png",
        "product_template_id": 397517,
        "release_date": null,
        "release_date_unix": null,
        "release_year": null,
        "retail_price_cents": 11000,
        "shoe_condition": "new_with_defects",
        "silhouette": "Air Jordan 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Black",
        "designer": "Tinker Hatfield",
        "details": "Black/Cement Grey-Summit White-Fire Red",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/020/806/485/original/461782_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 461782,
        "keywords": [
          "black cement",
          "bred",
          "jordan 4 bred"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/020/806/485/original/461782_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 4 Retro OG 'Bred' 2019",
        "nickname": "Bred",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/020/806/485/original/461782_00.png.png",
        "product_template_id": 461782,
        "release_date": "2019-05-04T23:59:59.000Z",
        "release_date_unix": 1557014399,
        "release_year": 2019,
        "retail_price_cents": 20000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Jordan 4",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Black",
        "designer": "Tinker Hatfield",
        "details": "Black/Infrared 23-Black",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/018/675/311/original/464372_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 464372,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/018/675/311/original/464372_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 6 Retro 'Infrared' 2019",
        "nickname": "Infrared",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/018/675/311/original/464372_00.png.png",
        "product_template_id": 464372,
        "release_date": "2019-02-16T23:59:59.000Z",
        "release_date_unix": 1550361599,
        "release_year": 2019,
        "retail_price_cents": 20000,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 6",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Black",
        "designer": "Tinker Hatfield",
        "details": "Black/Metallic Gold-White",
        "gender": [
          "women"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/021/042/384/original/500924_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 500924,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/021/042/384/original/500924_00.png.png",
        "midsole": "Air",
        "name": "Wmns Air Jordan 12 Retro 'Reptile'",
        "nickname": "Reptile",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/021/042/384/original/500924_00.png.png",
        "product_template_id": 500924,
        "release_date": "2019-05-17T07:00:00.000Z",
        "release_date_unix": 1558076400,
        "release_year": 2019,
        "retail_price_cents": 19000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Jordan 12",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "no_original_box",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Black",
        "designer": "Tinker Hatfield",
        "details": "Black/White-Gum Light Brown",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/018/071/547/original/479524_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 479524,
        "keywords": [
          "promoted1"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/018/071/547/original/479524_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 4 Retro 'Laser'",
        "nickname": "Laser, 30th Anniversary",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/018/071/547/original/479524_00.png.png",
        "product_template_id": 479524,
        "release_date": "2019-01-19T23:59:59.000Z",
        "release_date_unix": 1547942399,
        "release_year": 2019,
        "retail_price_cents": 20000,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 4",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ],
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Blue",
        "designer": "Peter Moore",
        "details": "White/Dark Powder Blue-Cone",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/012/219/518/original/335047_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 335047,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/012/219/518/original/335047_00.png.png",
        "midsole": "Air",
        "name": "OFF-WHITE x Air Jordan 1 Retro High OG 'UNC'",
        "nickname": "UNC",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/012/219/518/original/335047_00.png.png",
        "product_template_id": 335047,
        "release_date": "2018-05-23T23:59:59.000Z",
        "release_date_unix": 1527119999,
        "release_year": 2018,
        "retail_price_cents": 19000,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Blue",
        "designer": "Tinker Hatfield",
        "details": "Ice Blue/Sail-Metallic Gold-University Red",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/021/474/777/original/TR_JSP_5_ICE.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 515029,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/021/474/777/original/TR_JSP_5_ICE.png.png",
        "midsole": "Air",
        "name": "Trophy Room x Air Jordan 5 Retro 'Ice Blue'",
        "nickname": "Ice Blue",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/021/474/777/original/TR_JSP_5_ICE.png.png",
        "product_template_id": 515029,
        "release_date": "2019-05-18T07:00:00.000Z",
        "release_date_unix": 1558162800,
        "release_year": 2019,
        "retail_price_cents": 20000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Jordan 5",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Blue",
        "designer": "Tinker Hatfield",
        "details": "university blue/varsity red-black",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/012/478/518/original/365514_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 365514,
        "keywords": [
          "travis scott"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/012/478/518/original/365514_00.png.png",
        "midsole": "Air",
        "name": "Travis Scott x Air Jordan 4 Retro 'Cactus Jack'",
        "nickname": "Cactus Jack",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/012/478/518/original/365514_00.png.png",
        "product_template_id": 365514,
        "release_date": "2018-06-09T23:59:59.000Z",
        "release_date_unix": 1528588799,
        "release_year": 2018,
        "retail_price_cents": 22500,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 4",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Brown",
        "designer": "Peter Moore",
        "details": "Gold Harvest/Black-Sail",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/016/152/710/original/402491_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 402491,
        "keywords": [
          "ROY"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/016/152/710/original/402491_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 1 Retro High OG 'Rookie of the Year'",
        "nickname": "Rookie of the Year",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/016/152/710/original/402491_00.png.png",
        "product_template_id": 402491,
        "release_date": "2018-11-17T23:59:59.000Z",
        "release_date_unix": 1542499199,
        "release_year": 2018,
        "retail_price_cents": 16000,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Brown",
        "designer": "Peter Moore",
        "details": "Sail/Dark Mocha-University Red-Black",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/018/783/111/original/488879_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 488879,
        "keywords": [
          "cactus jack"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/018/783/111/original/488879_00.png.png",
        "midsole": "Air",
        "name": "Travis Scott x Air Jordan 1 Retro High OG 'Mocha'",
        "nickname": "Mocha",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/018/783/111/original/488879_00.png.png",
        "product_template_id": 488879,
        "release_date": "2019-05-11T23:59:59.000Z",
        "release_date_unix": 1557619199,
        "release_year": 2019,
        "retail_price_cents": 16000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Jordan 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Brown",
        "designer": "Tinker Hatfield",
        "details": "Shimmer/Mahogany Mink-Velvet Brown-Tough Red",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/021/321/847/original/473391_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 473391,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/021/321/847/original/473391_00.png.png",
        "midsole": "Air",
        "name": "Patta x Air Jordan 7 Retro OG SP 'Shimmer'",
        "nickname": "Shimmer",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/021/321/847/original/473391_00.png.png",
        "product_template_id": 473391,
        "release_date": "2019-05-18T07:00:00.000Z",
        "release_date_unix": 1558162800,
        "release_year": 2019,
        "retail_price_cents": 20000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Jordan 7",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "badly_damaged",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "collection_slugs": [
          "air-jordan-1",
          "all-star-weekend",
          "quarterly-sneaker-trends"
        ],
        "color": "Green",
        "designer": "Peter Moore",
        "details": "Turbo Green/White-Light Smoke Grey-Sail",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/018/552/901/original/404758_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 404758,
        "keywords": [
          "AJ1"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/018/552/901/original/404758_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 1 Retro High OG 'Turbo Green'",
        "nickname": "Turbo Green",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/018/552/901/original/404758_00.png.png",
        "product_template_id": 404758,
        "release_date": "2019-02-15T23:59:59.000Z",
        "release_date_unix": 1550275199,
        "release_year": 2019,
        "retail_price_cents": 16000,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Pink",
        "designer": "Peter Moore",
        "details": "Black/Crimson Tint-Hyper Pink-White",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/020/249/059/original/485842_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 485842,
        "keywords": [
          "underRetail"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/020/249/059/original/485842_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 1 Retro High OG 'Crimson Tint'",
        "nickname": "Crimson Tint",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/020/249/059/original/485842_00.png.png",
        "product_template_id": 485842,
        "release_date": "2019-04-12T23:59:59.000Z",
        "release_date_unix": 1555113599,
        "release_year": 2019,
        "retail_price_cents": 16000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Jordan 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Pink",
        "designer": "Tinker Hatfield",
        "details": "White/Black-Pink",
        "gender": [
          "women"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/021/357/907/original/478963_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 478963,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/021/357/907/original/478963_00.png.png",
        "midsole": "Air",
        "name": "Wmns Air Jordan 11 Retro Low 'Pink Snakeskin'",
        "nickname": "Pink Snakeskin",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/021/357/907/original/478963_00.png.png",
        "product_template_id": 478963,
        "release_date": "2019-05-07T07:00:00.000Z",
        "release_date_unix": 1557212400,
        "release_year": 2019,
        "retail_price_cents": 18500,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 11",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Purple",
        "designer": "Peter Moore",
        "details": "Court Purple/Sail-University Gold-Black",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/020/270/533/original/CD6578_507.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 494872,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/020/270/533/original/CD6578_507.png.png",
        "midsole": "Air",
        "name": "Air Jordan 1 Retro High SB 'Lakers'",
        "nickname": "Lakers vs. Bulls",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/020/270/533/original/CD6578_507.png.png",
        "product_template_id": 494872,
        "release_date": "2019-05-25T07:00:00.000Z",
        "release_date_unix": 1558767600,
        "release_year": 2019,
        "retail_price_cents": 17500,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Jordan 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Red",
        "designer": "Peter Moore",
        "details": "Gym Red/Summit White-Black",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/009/559/594/original/144690_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 144690,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/009/559/594/original/144690_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 1 Retro High OG 'Bred Toe'",
        "nickname": "Bred Toe",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/009/559/594/original/144690_00.png.png",
        "product_template_id": 144690,
        "release_date": "2018-02-24T23:59:59.000Z",
        "release_date_unix": 1519516799,
        "release_year": 2018,
        "retail_price_cents": 16000,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Red",
        "designer": "Peter Moore",
        "details": "Gym Red/White-Black-Photo Blue",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/016/867/969/original/478648_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 478648,
        "keywords": [
          "Chicago Crystal",
          "spider man",
          "spider verse"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/016/867/969/original/478648_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 1 Retro High OG 'Origin Story'",
        "nickname": "Origin Story, Spider-Man",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/016/867/969/original/478648_00.png.png",
        "product_template_id": 478648,
        "release_date": "2018-12-14T23:59:59.000Z",
        "release_date_unix": 1544831999,
        "release_year": 2018,
        "retail_price_cents": 16000,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "no_original_box",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Red",
        "designer": "Tinker Hatfield",
        "details": "Gym Red/Gym Red-Black",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/016/596/414/original/376931_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 376931,
        "keywords": [
          "Twelve"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/016/596/414/original/376931_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 12 Retro 'Gym Red'",
        "nickname": "Gym Red",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/016/596/414/original/376931_00.png.png",
        "product_template_id": 376931,
        "release_date": "2018-11-23T23:59:59.000Z",
        "release_date_unix": 1543017599,
        "release_year": 2018,
        "retail_price_cents": 19000,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 12",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "Red",
        "designer": "Tinker Hatfield",
        "details": "Light Bone/University Red-Sail-Black",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/021/219/116/original/CD6846_002.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 461771,
        "keywords": [
          "underRetail"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/021/219/116/original/CD6846_002.png.png",
        "midsole": "Air",
        "name": "Air Jordan 11 Retro Low 'Light Bone Snakeskin'",
        "nickname": "Light Bone Snakeskin",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/021/219/116/original/CD6846_002.png.png",
        "product_template_id": 461771,
        "release_date": "2019-05-18T07:00:00.000Z",
        "release_date_unix": 1558162800,
        "release_year": 2019,
        "retail_price_cents": 18500,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Jordan 11",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "White",
        "designer": "Peter Moore",
        "details": "Light Bone/Crimson Tint-Hyper Pink-Black",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/021/147/976/original/497870_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 497870,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/021/147/976/original/497870_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 1 Retro High SB 'Light Bone'",
        "nickname": "Light Bone",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/021/147/976/original/497870_00.png.png",
        "product_template_id": 497870,
        "release_date": "2019-05-25T07:00:00.000Z",
        "release_date_unix": 1558767600,
        "release_year": 2019,
        "retail_price_cents": null,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Jordan 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "White",
        "designer": "Peter Moore",
        "details": "Sail/Black-Phantom-University Red",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/020/095/762/original/411931_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 411931,
        "keywords": [
          "underRetail"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/020/095/762/original/411931_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 1 Retro High OG 'Phantom'",
        "nickname": "Phantom",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/020/095/762/original/411931_00.png.png",
        "product_template_id": 411931,
        "release_date": "2019-03-30T23:59:59.000Z",
        "release_date_unix": 1553990399,
        "release_year": 2019,
        "retail_price_cents": 16000,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ],
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
        "color": "White",
        "designer": "Peter Moore",
        "details": "White/White-Gum Yellow",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/021/317/617/original/SP_AJ1_LOW_BP.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 514029,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/021/317/617/original/SP_AJ1_LOW_BP.png.png",
        "midsole": "Air",
        "name": "Sneaker Politics x Air Jordan 1 Low 'Block Party'",
        "nickname": "Block Party",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/021/317/617/original/SP_AJ1_LOW_BP.png.png",
        "product_template_id": 514029,
        "release_date": "2019-05-10T07:00:00.000Z",
        "release_date_unix": 1557471600,
        "release_year": 2019,
        "retail_price_cents": 10000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Jordan 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "no_original_box",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],

        "color": "White",
        "designer": "Tinker Hatfield",
        "details": "Platinum Tint/Sail-University Red",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/015/392/851/original/429772_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 429772,
        "keywords": [
          "underRetail"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/015/392/851/original/429772_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 11 Retro 'Platinum Tint'",
        "nickname": "Platinum Tint",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/015/392/851/original/429772_00.png.png",
        "product_template_id": 429772,
        "release_date": "2018-10-27T23:59:59.000Z",
        "release_date_unix": 1540684799,
        "release_year": 2018,
        "retail_price_cents": 22000,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 11",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "no_original_box",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],

        "color": "White",
        "designer": "Tinker Hatfield",
        "details": "White/Black-Dark Concord",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/016/934/177/original/351614_00.png",
        "has_picture": true,
        "has_stock": true,
        "id": 351614,
        "keywords": [
          "Concord"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/016/934/177/original/351614_00.png",
        "midsole": "Air",
        "name": "Air Jordan 11 Retro 'Concord' 2018",
        "nickname": "Concord",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/016/934/177/original/351614_00.png",
        "product_template_id": 351614,
        "release_date": "2018-12-08T23:59:59.000Z",
        "release_date_unix": 1544313599,
        "release_year": 2018,
        "retail_price_cents": 22000,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 11",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ],
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],

        "color": "White",
        "designer": "Tinker Hatfield",
        "details": "White/Black-Navy",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/020/310/667/original/459705_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 459705,
        "keywords": [
          "underRetail"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/020/310/667/original/459705_00.png.png",
        "midsole": "",
        "name": "Air Jordan 11 Retro Low 'Navy Snakeskin' 2019",
        "nickname": "Snakeskin",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/020/310/667/original/459705_00.png.png",
        "product_template_id": 459705,
        "release_date": "2019-04-19T23:59:59.000Z",
        "release_date_unix": 1555718399,
        "release_year": 2019,
        "retail_price_cents": 18500,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 11",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "no_original_box",
        "brand_name": "Air Jordan",
        "category": [
          "lifestyle"
        ],
     
        "color": "White",
        "designer": "Tinker Hatfield",
        "details": "White/Fire Red-Tech Grey-Black",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/008/654/831/original/31342_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 31342,
        "keywords": [
          "cement",
          "white cement"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/008/654/831/original/31342_00.png.png",
        "midsole": "Air",
        "name": "Air Jordan 4 Retro OG 'White Cement' 2016",
        "nickname": "White Cement",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/008/654/831/original/31342_00.png.png",
        "product_template_id": 31342,
        "release_date": "2016-02-13T08:00:00.000Z",
        "release_date_unix": 1455350400,
        "release_year": 2016,
        "retail_price_cents": 22000,
        "shoe_condition": "used",
        "silhouette": "Air Jordan 4",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Champion",
        "category": [
          "lifestyle"
        ],
        "color": "Black",
        "designer": "",
        "details": "Black/White/Red",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/015/567/335/original/CM100018M.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 468155,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/015/567/335/original/CM100018M.png.png",
        "midsole": "",
        "name": "Rally Pro 'Black'",
        "nickname": "Black",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/015/567/335/original/CM100018M.png.png",
        "product_template_id": 468155,
        "release_date": null,
        "release_date_unix": null,
        "release_year": null,
        "retail_price_cents": 10000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Rally Pro",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Converse",
        "category": [
          "lifestyle"
        ],
       
        "color": "Cream",
        "designer": "Marquis Mills",
        "details": "Cream/Multicolor",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/018/552/840/original/476518_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 476518,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/018/552/840/original/476518_00.png.png",
        "midsole": "",
        "name": "Tyler, The Creator x Foot Locker x Chuck 70 'Artist Series'",
        "nickname": "Artist Series",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/018/552/840/original/476518_00.png.png",
        "product_template_id": 476518,
        "release_date": "2018-11-26T23:59:59.000Z",
        "release_date_unix": 1543276799,
        "release_year": 2018,
        "retail_price_cents": 10000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Chuck 70",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          13,
          14,
          15,
          3,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "no_original_box",
        "brand_name": "Converse",
        "category": [
          "lifestyle"
        ],
        
        "color": "White",
        "designer": "Marquis Mills",
        "details": "Milk",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/015/298/767/original/77243_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 77243,
        "keywords": [
          "CDG"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/015/298/767/original/77243_00.png.png",
        "midsole": "",
        "name": "Comme des Garçons x Chuck Taylor All Star Hi 'Milk'",
        "nickname": "Milk",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/015/298/767/original/77243_00.png.png",
        "product_template_id": 77243,
        "release_date": "2015-05-14T23:59:59.000Z",
        "release_date_unix": 1431647999,
        "release_year": 2015,
        "retail_price_cents": 12000,
        "shoe_condition": "used",
        "silhouette": "Chuck Taylor All Star",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          13,
          14,
          15,
          3,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Gucci",
        "category": [
          "other"
        ],
        "color": "Black",
        "designer": "",
        "details": "Black",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/009/249/006/original/259509_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 259509,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/009/249/006/original/259509_00.png.png",
        "midsole": "",
        "name": "Gucci Pursuit '72 Rubber Slide 'Black'",
        "nickname": "Black",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/009/249/006/original/259509_00.png.png",
        "product_template_id": 259509,
        "release_date": null,
        "release_date_unix": null,
        "release_year": null,
        "retail_price_cents": 21000,
        "shoe_condition": "used",
        "silhouette": "Gucci Slide",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Nike",
        "category": [
          "basketball"
        ],
        "color": "Black",
        "designer": "Benjamin Nethongkome",
        "details": "Black/White-Bright Crimson",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/020/840/270/original/491192_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 491192,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/020/840/270/original/491192_00.png.png",
        "midsole": "Air",
        "name": "Kyrie 5 'Friends'",
        "nickname": "Friends",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/020/840/270/original/491192_00.png.png",
        "product_template_id": 491192,
        "release_date": "2019-05-16T07:00:00.000Z",
        "release_date_unix": 1557990000,
        "release_year": 2019,
        "retail_price_cents": 13000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Kyrie 5",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "no_original_box",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],
        "color": "Black",
        "designer": "Christian Tresser",
        "details": "Black/Reflect Silver-Blue Lagoon",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/020/627/570/original/491891_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 491891,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/020/627/570/original/491891_00.png.png",
        "midsole": "Air",
        "name": "Air Max 97 'On Air: Neon Seoul'",
        "nickname": "Neon Seoul",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/020/627/570/original/491891_00.png.png",
        "product_template_id": 491891,
        "release_date": "2019-04-13T07:00:00.000Z",
        "release_date_unix": 1555138800,
        "release_year": 2019,
        "retail_price_cents": 20000,
        "shoe_condition": "used",
        "silhouette": "Air Max 97",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],
       
        "color": "Black",
        "designer": "Jerry Lorenzo",
        "details": "Black/Black-Fossil",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/021/545/549/original/489359_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 489359,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/021/545/549/original/489359_00.png.png",
        "midsole": "Air",
        "name": "Air Fear Of God Raid 'Black'",
        "nickname": "Black",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/021/545/549/original/489359_00.png.png",
        "product_template_id": 489359,
        "release_date": "2019-05-17T07:00:00.000Z",
        "release_date_unix": 1558076400,
        "release_year": 2019,
        "retail_price_cents": 19000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Fear Of God Strap",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],
       
        "color": "Black",
        "designer": "Tinker Hatfield",
        "details": "Black/Black-Cone-White",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/017/763/484/original/466439_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 466439,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/017/763/484/original/466439_00.png.png",
        "midsole": "Air",
        "name": "OFF-WHITE x Air Max 90 'Black'",
        "nickname": "Black",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/017/763/484/original/466439_00.png.png",
        "product_template_id": 466439,
        "release_date": "2019-02-07T23:59:59.000Z",
        "release_date_unix": 1549583999,
        "release_year": 2019,
        "retail_price_cents": 16000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Max 90",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "no_original_box",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],
        
        "color": "Black",
        "designer": "Tobie Hatfield",
        "details": "Black/White/Cone",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/012/750/761/original/351623_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 351623,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/012/750/761/original/351623_00.png.png",
        "midsole": "Air",
        "name": "OFF-WHITE x Air Presto 'Black'",
        "nickname": "Black",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/012/750/761/original/351623_00.png.png",
        "product_template_id": 351623,
        "release_date": "2018-07-27T23:59:59.000Z",
        "release_date_unix": 1532735999,
        "release_year": 2018,
        "retail_price_cents": 16000,
        "shoe_condition": "used",
        "silhouette": "Air Presto",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ],
        
      },
      {
        "box_condition": "no_original_box",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],
        
        "color": "Blue",
        "designer": "",
        "details": "Varsity Blue/Del Sol-Varsity Red-Black",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/019/246/220/original/491897_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 491897,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/019/246/220/original/491897_00.png.png",
        "midsole": "",
        "name": "Sacai x LDV Waffle 'Varsity Blue'",
        "nickname": "Varsity Blue",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/019/246/220/original/491897_00.png.png",
        "product_template_id": 491897,
        "release_date": "2019-05-30T07:00:00.000Z",
        "release_date_unix": 1559199600,
        "release_year": 2019,
        "retail_price_cents": 18000,
        "shoe_condition": "new_no_defects",
        "silhouette": "LDV Waffle",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ],
        
      },
      {
        "box_condition": "missing_lid",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],

        "color": "Cream",
        "designer": "Bill Bowerman",
        "details": "Sail/Obsidian-Total Crimson",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/021/545/501/original/507173_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 507173,
        "keywords": [
          "underRetail"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/021/545/501/original/507173_00.png.png",
        "midsole": null,
        "name": "Blazer Mid '77 Vintage 'City Pride Chicago'",
        "nickname": "City Pride Chicago",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/021/545/501/original/507173_00.png.png",
        "product_template_id": 507173,
        "release_date": "2019-05-03T07:00:00.000Z",
        "release_date_unix": 1556866800,
        "release_year": 2019,
        "retail_price_cents": 11000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Blazer",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],
    
        "color": "Multi-Color",
        "designer": "",
        "details": "Black/Bright Crimson",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/020/249/043/original/494127_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 494127,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/020/249/043/original/494127_00.png.png",
        "midsole": "Air",
        "name": "Atmos x Air Max 2 Light QS 'Logos'",
        "nickname": "Logos",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/020/249/043/original/494127_00.png.png",
        "product_template_id": 494127,
        "release_date": "2019-04-05T07:00:00.000Z",
        "release_date_unix": 1554447600,
        "release_year": 2019,
        "retail_price_cents": 16000,
        "shoe_condition": "used",
        "silhouette": "Air Max 2 Light",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "badly_damaged",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],
        "color": "Orange",
        "designer": "Bruce Kilgore",
        "details": "Team Orange/White-Black-Tour Yellow",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/019/994/877/original/AJ7747_800.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 443766,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/019/994/877/original/AJ7747_800.png.png",
        "midsole": "Air",
        "name": "Air Force 1 '07 LV8 'Overbranding'",
        "nickname": "Overbranding",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/019/994/877/original/AJ7747_800.png.png",
        "product_template_id": 443766,
        "release_date": "2018-08-30T23:59:59.000Z",
        "release_date_unix": 1535673599,
        "release_year": 2018,
        "retail_price_cents": 10000,
        "shoe_condition": "used",
        "silhouette": "Air Force 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "missing_lid",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],
       
        "color": "Red",
        "designer": "Tinker Hatfield",
        "details": "Mars Stone/Magma Orange",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/019/804/999/original/488028_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 488028,
        "keywords": [
          "promoted1",
          "underRetail"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/019/804/999/original/488028_00.png.png",
        "midsole": "Air",
        "name": "Air Max 90 QS 'Mars Landing'",
        "nickname": "Mars Landing",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/019/804/999/original/488028_00.png.png",
        "product_template_id": 488028,
        "release_date": "2019-03-16T23:59:59.000Z",
        "release_date_unix": 1552780799,
        "release_year": 2019,
        "retail_price_cents": 16000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Max 90",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],
        
        "color": "Tan",
        "designer": "Tinker Hatfield",
        "details": "Desert Ore/Desert Ore-Hyper Jade-Bright Mango",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/017/794/455/original/394710_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 394710,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/017/794/455/original/394710_00.png.png",
        "midsole": "Air",
        "name": "OFF-WHITE x Air Max 90 'Desert Ore'",
        "nickname": "Desert Ore",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/017/794/455/original/394710_00.png.png",
        "product_template_id": 394710,
        "release_date": "2019-02-07T23:59:59.000Z",
        "release_date_unix": 1549583999,
        "release_year": 2019,
        "retail_price_cents": 16000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Max 90",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],
      
        "color": "White",
        "designer": "Andreas Harlow",
        "details": "White/Total Orange-Black",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/010/564/058/original/303229_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 303229,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/010/564/058/original/303229_00.png.png",
        "midsole": "Air",
        "name": "OFF-WHITE x Air VaporMax 'Part 2'",
        "nickname": "Part 2",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/010/564/058/original/303229_00.png.png",
        "product_template_id": 303229,
        "release_date": "2018-04-14T23:59:59.000Z",
        "release_date_unix": 1523750399,
        "release_year": 2018,
        "retail_price_cents": 25000,
        "shoe_condition": "used",
        "silhouette": "Air VaporMax",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],
        
        "color": "White",
        "designer": "Bruce Kilgore",
        "details": "Sail/Gum Light Brown/Sail",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/013/832/092/original/306892_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 306892,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/013/832/092/original/306892_00.png.png",
        "midsole": "Air",
        "name": "Travis Scott x Air Force 1 'Sail'",
        "nickname": "Sail",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/013/832/092/original/306892_00.png.png",
        "product_template_id": 306892,
        "release_date": "2018-08-10T23:59:59.000Z",
        "release_date_unix": 1533945599,
        "release_year": 2018,
        "retail_price_cents": 15000,
        "shoe_condition": "used",
        "silhouette": "Air Force 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],
        
        "color": "White",
        "designer": "Bruce Kilgore",
        "details": "White/Black-Hyper Crimson",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/020/881/688/original/508101_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 508101,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/020/881/688/original/508101_00.png.png",
        "midsole": "Air",
        "name": "Steven Harrington x Air Force 1 Low Flyleather QS 'Earth Day'",
        "nickname": "Earth Day",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/020/881/688/original/508101_00.png.png",
        "product_template_id": 508101,
        "release_date": "2019-04-22T23:59:59.000Z",
        "release_date_unix": 1555977599,
        "release_year": 2019,
        "retail_price_cents": 10000,
        "shoe_condition": "new_with_defects",
        "silhouette": "Air Force 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],
        
        "color": "White",
        "designer": "Bruce Kilgore",
        "details": "White/Black-White",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/019/367/662/original/484799_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 484799,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/019/367/662/original/484799_00.png.png",
        "midsole": "Air",
        "name": "Air Force 1 Low 'Have a Nike Day - White'",
        "nickname": "Have a Nike Day - White",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/019/367/662/original/484799_00.png.png",
        "product_template_id": 484799,
        "release_date": "2019-02-26T23:59:59.000Z",
        "release_date_unix": 1551225599,
        "release_year": 2019,
        "retail_price_cents": 10000,
        "shoe_condition": "used",
        "silhouette": "Air Force 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "no_original_box",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],
        "color": "White",
        "designer": "Bruce Kilgore",
        "details": "White/University Blue",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/018/898/008/original/482531_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 482531,
        "keywords": [],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/018/898/008/original/482531_00.png.png",
        "midsole": "Air",
        "name": "Air Force 1 '07 Low 'University Blue'",
        "nickname": "University Blue",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/018/898/008/original/482531_00.png.png",
        "product_template_id": 482531,
        "release_date": null,
        "release_date_unix": null,
        "release_year": null,
        "retail_price_cents": 9000,
        "shoe_condition": "used",
        "silhouette": "Air Force 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "no_original_box",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],
        
        "color": "White",
        "designer": "Bruce Kilgore",
        "details": "White/White",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/010/222/352/original/240_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 240,
        "keywords": [
          "underRetail"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/010/222/352/original/240_00.png.png",
        "midsole": "Air",
        "name": "Air Force 1 '07 'White'",
        "nickname": "White",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/010/222/352/original/240_00.png.png",
        "product_template_id": 240,
        "release_date": null,
        "release_date_unix": null,
        "release_year": null,
        "retail_price_cents": 9000,
        "shoe_condition": "used",
        "silhouette": "Air Force 1",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],

        "color": "White",
        "designer": "Christian Tresser",
        "details": "Game Royal/Metallic Silver-White",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/021/562/245/original/480142_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 480142,
        "keywords": [
          "ASG",
          "All Star Game",
          "underRetail"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/021/562/245/original/480142_00.png.png",
        "midsole": "Air",
        "name": "Air Max 97 'All Star Jersey'",
        "nickname": "All Star Jersey",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/021/562/245/original/480142_00.png.png",
        "product_template_id": 480142,
        "release_date": "2019-02-08T23:59:59.000Z",
        "release_date_unix": 1549670399,
        "release_year": 2019,
        "retail_price_cents": 16000,
        "shoe_condition": "new_with_defects",
        "silhouette": "Air Max 97",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],
       
        "color": "White",
        "designer": "Jerry Lorenzo",
        "details": "Light Bone/Black-Sail",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/020/627/586/original/487222_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 487222,
        "keywords": [
          "underRetail"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/020/627/586/original/487222_00.png.png",
        "midsole": "Air",
        "name": "Air Fear Of God Raid 'Light Bone'",
        "nickname": "Light Bone",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/020/627/586/original/487222_00.png.png",
        "product_template_id": 487222,
        "release_date": "2019-04-27T07:00:00.000Z",
        "release_date_unix": 1556348400,
        "release_year": 2019,
        "retail_price_cents": 19000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Fear Of God Strap",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Nike",
        "category": [
          "lifestyle"
        ],

        "color": "White",
        "designer": "Jerry Lorenzo",
        "details": "Pure Platinum/Black-Sail",
        "gender": [
          "men"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/020/737/643/original/504006_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 504006,
        "keywords": [
          "underRetail"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/020/737/643/original/504006_00.png.png",
        "midsole": "Air",
        "name": "Air Fear Of God Moc 'Pure Platinum'",
        "nickname": "Pure Platinum",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/020/737/643/original/504006_00.png.png",
        "product_template_id": 504006,
        "release_date": "2019-04-27T07:00:00.000Z",
        "release_date_unix": 1556348400,
        "release_year": 2019,
        "retail_price_cents": 17000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air Fear of God Moccasin",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          16,
          16.5,
          17,
          17.5,
          18,
          3.5,
          4,
          4.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      },
      {
        "box_condition": "good_condition",
        "brand_name": "Nike",
        "category": [
          "running"
        ],
        
        "color": "Grey",
        "designer": "Andreas Harlow",
        "details": "Green Mist/Light Beige Chalk",
        "gender": [
          "women"
        ],
        "grid_picture_url": "https://image.goat.com/375/attachments/product_template_pictures/images/021/321/832/original/503571_00.png.png",
        "has_picture": true,
        "has_stock": true,
        "id": 503571,
        "keywords": [
          "CPFM"
        ],
        "main_picture_url": "https://image.goat.com/750/attachments/product_template_pictures/images/021/321/832/original/503571_00.png.png",
        "midsole": "Air",
        "name": "Cactus Plant Flea Market x Wmns Air VaporMax 2019 'CPFM'",
        "nickname": "CPFM",
        "original_picture_url": "https://image.goat.com/attachments/product_template_pictures/images/021/321/832/original/503571_00.png.png",
        "product_template_id": 503571,
        "release_date": "2019-05-14T07:00:00.000Z",
        "release_date_unix": 1557817200,
        "release_year": 2019,
        "retail_price_cents": 25000,
        "shoe_condition": "new_no_defects",
        "silhouette": "Air VaporMax",
        "size_range": [
          10,
          10.5,
          11,
          11.5,
          12,
          12.5,
          13,
          13.5,
          14,
          14.5,
          15,
          15.5,
          5,
          5.5,
          6,
          6.5,
          7,
          7.5,
          8,
          8.5,
          9,
          9.5
        ]
      }

    ]);
    const [show, setShow] = useState(false);
    const [clickedShoe, setClickedShoe]=useState(null);
    const handleClose = () => {
      setClickedShoe([]);
      setShow(false);
      
    };
    const handleShow = (id) => {
      const newId=id;
      // const sh = shoes.filter(sh=> sh.id===newId);
      
      // const shoe=[...sh];
      setClickedShoe(newId);
      setShow(true);
      // console.log(shoe);
    };
    const cs=shoes.filter(shoe=> shoe.id===clickedShoe)[0];
    console.log(cs);
    
    return(
        
           <div className="Cards">
             
           {shoes.map(shoe=> <Card shoe={shoe} click={()=>{
             handleShow(shoe.id);
             }}/>)}
           
           <Modals show={show} hide={handleClose}  shoe={cs}/>
           
            
          </div>
          
        
    );
}
export default HomePage;